<section class="section section-margin section-image">
    <div class="container">
        <figure class="image-container image-rounded">
            <img src="<?= $image->getUrl('image') ?>" class="img-fluid d-block mx-auto">
            <?php if (!empty($caption)): ?>
                <figcaption class="text-right text-muted text-sm image-caption">
                    <?= $caption ?>
                </figcaption>
            <?php endif; ?>
        </figure>
    </div>
</section>
